"""
Feature engineering for PCA -> HMM -> SV pipeline.

Curated feature set (v4): 19 features spanning distinct regime dimensions.
15 selected for PCA via FEATURE_SUBSET in config.py.

Feature groups:
  - Volatility state    (VIX, VRP)
  - Vol dynamics        (rv_ratio_10_63, vix_ts_slope, SPY_volvol20)
  - Cross-asset risk    (SPY_TLT_corr63, credit_stress, hy_spread)
  - Macro               (yield_slope)
  - Return dynamics     (SPY_ret, SPY_skew20, SPY_ac1_20)
  - Market structure    (eigen_conc, SPY_dd63)
  - Liquidity           (SPY_rel_volume, SPY_vol_adj_ret)
  - SV-specific         (SPY_rv10_lag5, SPY_rv10_lag10)
  - Leverage / fragility (lev_effect20)
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import joblib
import os

from config import (
    TICKERS, SHORT_WINDOW, MED_WINDOW, LONG_WINDOW,
    DATA_DIR, MODEL_DIR,
)


# ── Volatility estimators ──────────────────────────────────────────

def _realized_vol(returns: pd.Series, window: int) -> pd.Series:
    """Annualized rolling standard deviation of returns."""
    return returns.rolling(window).std() * np.sqrt(252)


def _parkinson_vol(high: pd.Series, low: pd.Series, window: int) -> pd.Series:
    """Parkinson (1980) high-low volatility estimator, rolling."""
    hl2 = (np.log(high / low)) ** 2 / (4 * np.log(2))
    return np.sqrt(hl2.rolling(window).mean() * 252)


def _garman_klass_vol(
    open_: pd.Series, high: pd.Series,
    low: pd.Series, close: pd.Series,
    window: int,
) -> pd.Series:
    """Garman-Klass (1980) OHLC volatility estimator, rolling."""
    hl2 = 0.5 * (np.log(high / low)) ** 2
    co2 = (2 * np.log(2) - 1) * (np.log(close / open_)) ** 2
    gk  = hl2 - co2
    return np.sqrt(gk.rolling(window).mean().clip(lower=0) * 252)


# ── Feature builder (v2 — curated) ─────────────────────────────────

# Features generated by build_features(), in order.
# Core 13 curated + 6 extras (autocorrelation, liquidity, SV-specific).
CURATED_FEATURES = [
    # Volatility state
    'VIX',               # implied vol (market forward expectation)
    'VRP',               # vol risk premium (implied - realized gap)
    # Vol dynamics
    'rv_ratio_10_63',    # vol term structure (short/long; >1 = spike)
    'vix_ts_slope',      # VIX term structure (contango / backwardation)
    'SPY_volvol20',      # vol-of-vol (discrete-time ξ analog)
    # Cross-asset risk
    'SPY_TLT_corr63',   # stock-bond correlation regime
    'credit_stress',     # HY vs Treasury flow (20d rolling)
    'hy_spread',         # absolute HY credit spread level
    # Macro
    'yield_slope',       # yield curve 10Y - 2Y
    # Return dynamics
    'SPY_ret',           # daily log return
    'SPY_skew20',        # rolling skewness (20d)
    'SPY_ac1_20',        # rolling first-order autocorrelation (20d)
    # Market structure
    'eigen_conc',        # eigenvalue concentration (one-factor signal)
    'SPY_dd63',          # 63d drawdown depth
    # Liquidity
    'SPY_rel_volume',    # relative volume vs 20d mean
    'SPY_vol_adj_ret',   # volume-normalized absolute return
    # SV-specific
    'SPY_rv10_lag5',     # lagged realized vol (5d)
    'SPY_rv10_lag10',    # lagged realized vol (10d)
    # Leverage / fragility
    'lev_effect20',      # return-vol correlation (leverage effect)
]


def build_features(market: pd.DataFrame) -> pd.DataFrame:
    """
    Build curated feature matrix from raw market data.

    14 features spanning distinct regime dimensions — no redundancy.
    Each feature captures one independent axis of market risk state.
    """
    f = pd.DataFrame(index=market.index)

    # ── Helper returns (needed for derived features) ───────────────
    spy_close = market.get('SPY_close')
    spy_ret: pd.Series | None = None
    if spy_close is not None:
        spy_ret = pd.Series(np.log(spy_close / spy_close.shift(1)),
                            index=market.index)
        f['SPY_ret'] = spy_ret

    tlt_ret: pd.Series | None = None
    if 'TLT_close' in market.columns:
        tlt_ret = pd.Series(
            np.log(market['TLT_close'] / market['TLT_close'].shift(1)),
            index=market.index)

    hyg_ret: pd.Series | None = None
    if 'HYG_close' in market.columns:
        hyg_ret = pd.Series(
            np.log(market['HYG_close'] / market['HYG_close'].shift(1)),
            index=market.index)

    # ── Volatility state ───────────────────────────────────────────
    rv10: pd.Series | None = None
    rv20: pd.Series | None = None
    rv63: pd.Series | None = None
    if spy_ret is not None:
        rv10 = _realized_vol(spy_ret, SHORT_WINDOW)
        rv20 = _realized_vol(spy_ret, MED_WINDOW)
        rv63 = _realized_vol(spy_ret, LONG_WINDOW)

    if 'VIX' in market.columns:
        f['VIX'] = market['VIX']

    # VRP: VIX - realized vol (20d) in vol points
    if 'VIX' in market.columns and rv20 is not None:
        f['VRP'] = market['VIX'] - rv20 * 100

    # ── Vol dynamics ───────────────────────────────────────────────
    if rv10 is not None and rv63 is not None:
        f['rv_ratio_10_63'] = rv10 / rv63.clip(lower=1e-6)

    if 'VIX' in market.columns and 'VIX3M' in market.columns:
        f['vix_ts_slope'] = market['VIX'] / market['VIX3M'].clip(lower=1) - 1

    # ── Cross-asset risk ───────────────────────────────────────────
    if spy_ret is not None and tlt_ret is not None:
        f['SPY_TLT_corr63'] = spy_ret.rolling(LONG_WINDOW).corr(tlt_ret)

    if hyg_ret is not None and tlt_ret is not None:
        f['credit_stress'] = (hyg_ret - tlt_ret).rolling(MED_WINDOW).mean()

    if 'hy_spread' in market.columns:
        f['hy_spread'] = market['hy_spread']

    # ── Macro ──────────────────────────────────────────────────────
    if 'yield_slope' in market.columns:
        f['yield_slope'] = market['yield_slope']

    # ── Return dynamics ────────────────────────────────────────────
    if spy_ret is not None:
        f['SPY_skew20'] = spy_ret.rolling(MED_WINDOW).skew()

    # ── Market structure ───────────────────────────────────────────
    # Eigenvalue concentration: needs multi-asset returns
    ret_cols = []
    for ticker in TICKERS:
        col = f'{ticker}_close'
        if col in market.columns:
            ret_cols.append(np.log(market[col] / market[col].shift(1)))
    if len(ret_cols) >= 3:
        ret_matrix = pd.concat(ret_cols, axis=1).values
        n = len(ret_matrix)
        eigen_vals = np.full(n, np.nan)
        for i in range(LONG_WINDOW - 1, n):
            window = ret_matrix[i - LONG_WINDOW + 1: i + 1]
            if np.isnan(window).any():
                continue
            cov = np.cov(window, rowvar=False)
            eigs = np.linalg.eigvalsh(cov)
            eigs = np.maximum(eigs, 0)
            total = eigs.sum()
            if total > 1e-12:
                eigen_vals[i] = eigs[-1] / total
        f['eigen_conc'] = eigen_vals

    if spy_close is not None:
        rolling_max = spy_close.rolling(LONG_WINDOW).max()
        f['SPY_dd63'] = spy_close / rolling_max - 1

    # ── Additional return dynamics ──────────────────────────────────

    # 22. Rolling first-order autocorrelation (20d, efficient proxy)
    #     ρ̂₁ ≈ Σ(r_t · r_{t-1}) / Σ(r_t²)
    if spy_ret is not None:
        ret_lag = spy_ret.shift(1)
        f['SPY_ac1_20'] = (
            (spy_ret * ret_lag).rolling(MED_WINDOW).sum()
            / (spy_ret ** 2).rolling(MED_WINDOW).sum().clip(lower=1e-12)
        )

    # ── Liquidity ──────────────────────────────────────────────────

    # 23. Relative volume (SPY volume vs 20d mean)
    if 'SPY_volume' in market.columns:
        vol_ma = market['SPY_volume'].rolling(MED_WINDOW).mean()
        f['SPY_rel_volume'] = market['SPY_volume'] / vol_ma.clip(lower=1)

    # 24. Volume-normalized absolute return (fragility proxy)
    if 'SPY_volume' in market.columns and spy_ret is not None:
        norm_vol = market['SPY_volume'] / market['SPY_volume'].rolling(LONG_WINDOW).mean()
        f['SPY_vol_adj_ret'] = spy_ret.abs() / norm_vol.clip(lower=0.1)

    # ── SV-specific features (critical for ρ, ϕ identification) ───

    # 25. Lagged realized vol (SV persistence ϕ support)
    if rv10 is not None:
        f['SPY_rv10_lag5'] = rv10.shift(5)
        f['SPY_rv10_lag10'] = rv10.shift(10)

    # 26. Vol-of-vol estimate (discrete-time ξ analog)
    if rv10 is not None:
        f['SPY_volvol20'] = rv10.rolling(MED_WINDOW).std()

    # 27. Leverage effect proxy (rolling corr between return and lagged vol change)
    #     Empirically measures ρ < 0 in Heston / SV models.
    #     vol_chg is shifted by 1 day for strict causality (avoid same-day info).
    if spy_ret is not None and rv10 is not None:
        vol_chg = rv10.diff().shift(1)
        f['lev_effect20'] = spy_ret.rolling(MED_WINDOW).corr(vol_chg)

    # ── Drop warm-up NaN rows ──────────────────────────────────────
    na_counts = f.isna().sum()
    binding = na_counts[na_counts > 0].sort_values(ascending=False)
    if not binding.empty:
        print(f"  Feature NaN counts (top 5 binding constraints):")
        for feat, cnt in binding.head(5).items():
            print(f"    {feat}: {cnt} NaN rows")

    f = f.dropna()

    assert len(f) >= 252, (
        f"Insufficient data after warm-up: {len(f)} rows (need >= 252). "
        f"Check data availability or reduce LONG_WINDOW."
    )

    return f


# ── Skewness correction ────────────────────────────────────────────

# Features that are non-negative and right-skewed → log(1+x) compresses
# the right tail so PCA doesn't over-weight crisis outliers and the
# symmetric Student-t emissions fit each regime more cleanly.
_LOG_TRANSFORM_COLS = {
    'VIX', 'rv_ratio_10_63',
    'hy_spread', 'eigen_conc',
}


def _fix_skew(features: pd.DataFrame) -> pd.DataFrame:
    """Apply log1p to right-skewed non-negative features in-place."""
    for col in _LOG_TRANSFORM_COLS:
        if col in features.columns:
            features[col] = np.log1p(features[col])
    return features


# ── Standardization ────────────────────────────────────────────────

def standardize(features: pd.DataFrame, scaler=None, fit=True):
    """
    Z-score standardize features.

    Returns
    -------
    X_scaled : ndarray (T x n_features)
    scaler   : fitted StandardScaler
    """
    if scaler is None:
        scaler = StandardScaler()
    if fit:
        X = scaler.fit_transform(features.values)
    else:
        X = scaler.transform(features.values)
    return X, scaler


# ── Convenience: build + scale + save ──────────────────────────────

def prepare_features(market=None):
    """
    Full feature pipeline:  build -> standardize -> save.
    If *market* is None, loads from DATA_DIR/market_data.csv.
    """
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(MODEL_DIR, exist_ok=True)

    if market is None:
        market = pd.read_csv(
            os.path.join(DATA_DIR, 'market_data.csv'),
            index_col=0, parse_dates=True,
        )

    features = build_features(market)
    features = _fix_skew(features)
    X_scaled, scaler = standardize(features)

    # Save raw features, scaled features (EDA only -- not for training), scaler
    features.to_csv(os.path.join(DATA_DIR, 'features_raw.csv'))
    pd.DataFrame(
        X_scaled, columns=features.columns, index=features.index,
    ).to_csv(os.path.join(DATA_DIR, 'features_scaled.csv'))
    joblib.dump(scaler, os.path.join(MODEL_DIR, 'scaler.pkl'))

    print(f"Features: {features.shape[1]} indicators x {features.shape[0]} days")
    print(f"  Columns: {list(features.columns)}")

    return features, X_scaled, scaler


if __name__ == '__main__':
    prepare_features()
