"""
Feature engineering for PCA -> HMM -> SV pipeline.

Curated feature set (v5): 17 features spanning distinct regime dimensions.
13 selected for PCA via FEATURE_SUBSET in config.py.

Feature groups:
  - Volatility state    (VIX, VRP)
  - Vol dynamics        (rv_ratio_10_63, vix_ts_slope, SPY_volvol20)
  - Cross-asset risk    (SPY_TLT_corr63, credit_stress)
  - Return dynamics     (SPY_ret, SPY_skew20, SPY_ac1_20)
  - Market structure    (eigen_conc, SPY_dd63)
  - Liquidity           (SPY_rel_volume, SPY_vol_adj_ret)
  - SV-specific         (SPY_rv10_lag5, SPY_rv10_lag10)
  - Leverage / fragility (lev_effect20)
"""

import pandas as pd
import numpy as np
import os

from config import (
    TICKERS, SHORT_WINDOW, MED_WINDOW, LONG_WINDOW,
    DATA_DIR, MODEL_DIR,
)


# ── Volatility estimators ──────────────────────────────────────────

def _realized_vol(returns: pd.Series, window: int) -> pd.Series:
    """Annualized rolling standard deviation of returns."""
    return returns.rolling(window).std() * np.sqrt(252)


def _parkinson_vol(high: pd.Series, low: pd.Series, window: int) -> pd.Series:
    """Parkinson (1980) high-low volatility estimator, rolling."""
    hl2 = (np.log(high / low)) ** 2 / (4 * np.log(2))
    return np.sqrt(hl2.rolling(window).mean() * 252)


def _garman_klass_vol(
    open_: pd.Series, high: pd.Series,
    low: pd.Series, close: pd.Series,
    window: int,
) -> pd.Series:
    """Garman-Klass (1980) OHLC volatility estimator, rolling."""
    hl2 = 0.5 * (np.log(high / low)) ** 2
    co2 = (2 * np.log(2) - 1) * (np.log(close / open_)) ** 2
    gk  = hl2 - co2
    return np.sqrt(gk.rolling(window).mean().clip(lower=0) * 252)


# ── Feature builder (v2 — curated) ─────────────────────────────────

# All 17 features generated by build_features(), in order.
# 13 are selected by FEATURE_SUBSET (config.py) for PCA.
CURATED_FEATURES = [
    # Volatility state
    'VIX',               # implied vol (market forward expectation)
    'VRP',               # vol risk premium (implied - realized gap)
    # Vol dynamics
    'rv_ratio_10_63',    # vol term structure (short/long; >1 = spike)
    'vix_ts_slope',      # VIX term structure (contango / backwardation)
    'SPY_volvol20',      # vol-of-vol (discrete-time ξ analog)
    # Cross-asset risk
    'SPY_TLT_corr63',   # stock-bond correlation regime
    'credit_stress',     # HY vs Treasury flow (20d rolling)
    # Return dynamics
    'SPY_ret',           # daily log return
    'SPY_skew20',        # rolling skewness (20d)
    'SPY_ac1_20',        # rolling first-order autocorrelation (20d)
    # Market structure
    'eigen_conc',        # eigenvalue concentration (one-factor signal)
    'SPY_dd63',          # 63d drawdown depth
    # Liquidity
    'SPY_rel_volume',    # relative volume vs 20d mean
    'SPY_vol_adj_ret',   # volume-normalized absolute return
    # SV-specific
    'SPY_rv10_lag5',     # lagged realized vol (5d)
    'SPY_rv10_lag10',    # lagged realized vol (10d)
    # Leverage / fragility
    'lev_effect20',      # return-vol correlation (leverage effect)
]


def build_features(market: pd.DataFrame) -> pd.DataFrame:
    """
    Build curated feature matrix from raw market data.

    19 features spanning distinct regime dimensions — no redundancy.
    Each feature captures one independent axis of market risk state.
    """
    f = pd.DataFrame(index=market.index)

    # ── Helper returns (needed for derived features) ───────────────
    spy_close = market.get('SPY_close')
    spy_ret: pd.Series | None = None
    if spy_close is not None:
        spy_ret = pd.Series(np.log(spy_close / spy_close.shift(1)),
                            index=market.index)
        f['SPY_ret'] = spy_ret

    tlt_ret: pd.Series | None = None
    if 'TLT_close' in market.columns:
        tlt_ret = pd.Series(
            np.log(market['TLT_close'] / market['TLT_close'].shift(1)),
            index=market.index)

    hyg_ret: pd.Series | None = None
    if 'HYG_close' in market.columns:
        hyg_ret = pd.Series(
            np.log(market['HYG_close'] / market['HYG_close'].shift(1)),
            index=market.index)

    # ── Volatility state ───────────────────────────────────────────
    rv10: pd.Series | None = None
    rv20: pd.Series | None = None
    rv63: pd.Series | None = None
    if spy_ret is not None:
        rv10 = _realized_vol(spy_ret, SHORT_WINDOW)
        rv20 = _realized_vol(spy_ret, MED_WINDOW)
        rv63 = _realized_vol(spy_ret, LONG_WINDOW)

    if 'VIX' in market.columns:
        f['VIX'] = market['VIX']

    # VRP: VIX - realized vol (20d) in vol points
    if 'VIX' in market.columns and rv20 is not None:
        f['VRP'] = market['VIX'] - rv20 * 100

    # ── Vol dynamics ───────────────────────────────────────────────
    if rv10 is not None and rv63 is not None:
        f['rv_ratio_10_63'] = rv10 / rv63.clip(lower=1e-6)

    if 'VIX' in market.columns and 'VIX3M' in market.columns:
        f['vix_ts_slope'] = market['VIX'] / market['VIX3M'].clip(lower=1) - 1

    # ── Cross-asset risk ───────────────────────────────────────────
    if spy_ret is not None and tlt_ret is not None:
        f['SPY_TLT_corr63'] = spy_ret.rolling(LONG_WINDOW).corr(tlt_ret)

    if hyg_ret is not None and tlt_ret is not None:
        f['credit_stress'] = (hyg_ret - tlt_ret).rolling(MED_WINDOW).mean()

    # ── Return dynamics ────────────────────────────────────────────
    if spy_ret is not None:
        f['SPY_skew20'] = spy_ret.rolling(MED_WINDOW).skew()

    # ── Market structure ───────────────────────────────────────────
    # Eigenvalue concentration: needs multi-asset returns
    ret_cols = []
    for ticker in TICKERS:
        col = f'{ticker}_close'
        if col in market.columns:
            ret_cols.append(np.log(market[col] / market[col].shift(1)))
    if len(ret_cols) >= 3:
        ret_matrix = pd.concat(ret_cols, axis=1).values
        n = len(ret_matrix)
        eigen_vals = np.full(n, np.nan)
        for i in range(LONG_WINDOW - 1, n):
            window = ret_matrix[i - LONG_WINDOW + 1: i + 1]
            if np.isnan(window).any():
                continue
            cov = np.cov(window, rowvar=False)
            eigs = np.linalg.eigvalsh(cov)
            eigs = np.maximum(eigs, 0)
            total = eigs.sum()
            if total > 1e-12:
                eigen_vals[i] = eigs[-1] / total
        f['eigen_conc'] = eigen_vals

    if spy_close is not None:
        rolling_max = spy_close.rolling(LONG_WINDOW).max()
        f['SPY_dd63'] = spy_close / rolling_max - 1

    # ── Additional return dynamics ──────────────────────────────────

    # 22. Rolling first-order autocorrelation (20d, efficient proxy)
    #     ρ̂₁ ≈ Σ(r_t · r_{t-1}) / Σ(r_t²)
    if spy_ret is not None:
        ret_lag = spy_ret.shift(1)
        f['SPY_ac1_20'] = (
            (spy_ret * ret_lag).rolling(MED_WINDOW).sum()
            / (spy_ret ** 2).rolling(MED_WINDOW).sum().clip(lower=1e-12)
        )

    # ── Liquidity ──────────────────────────────────────────────────

    # 23. Relative volume (SPY volume vs 20d mean)
    if 'SPY_volume' in market.columns:
        vol_ma = market['SPY_volume'].rolling(MED_WINDOW).mean()
        f['SPY_rel_volume'] = market['SPY_volume'] / vol_ma.clip(lower=1)

    # 24. Volume-normalized absolute return (fragility proxy)
    if 'SPY_volume' in market.columns and spy_ret is not None:
        norm_vol = market['SPY_volume'] / market['SPY_volume'].rolling(LONG_WINDOW).mean()
        f['SPY_vol_adj_ret'] = spy_ret.abs() / norm_vol.clip(lower=0.1)

    # ── SV-specific features (critical for ρ, ϕ identification) ───

    # 25. Lagged realized vol (SV persistence ϕ support)
    if rv10 is not None:
        f['SPY_rv10_lag5'] = rv10.shift(5)
        f['SPY_rv10_lag10'] = rv10.shift(10)

    # 26. Vol-of-vol estimate (discrete-time ξ analog)
    if rv10 is not None:
        f['SPY_volvol20'] = rv10.rolling(MED_WINDOW).std()

    # 27. Leverage effect proxy (rolling corr between return and lagged vol change)
    #     Empirically measures ρ < 0 in Heston / SV models.
    #     vol_chg is shifted by 1 day for strict causality (avoid same-day info).
    if spy_ret is not None and rv10 is not None:
        vol_chg = rv10.diff().shift(1)
        f['lev_effect20'] = spy_ret.rolling(MED_WINDOW).corr(vol_chg)

    # ── Drop warm-up NaN rows ──────────────────────────────────────
    na_counts = f.isna().sum()
    binding = na_counts[na_counts > 0].sort_values(ascending=False)
    if not binding.empty:
        print(f"  Feature NaN counts (top 5 binding constraints):")
        for feat, cnt in binding.head(5).items():
            print(f"    {feat}: {cnt} NaN rows")

    f = f.dropna()

    assert len(f) >= 252, (
        f"Insufficient data after warm-up: {len(f)} rows (need >= 252). "
        f"Check data availability or reduce LONG_WINDOW."
    )

    return f


# ── Skewness correction ────────────────────────────────────────────

# Features that are non-negative and right-skewed → log(1+x) compresses
# the right tail so PCA doesn't over-weight crisis outliers and the
# symmetric Student-t emissions fit each regime more cleanly.
_LOG_TRANSFORM_COLS = {
    'VIX', 'rv_ratio_10_63',
    'eigen_conc',
}


def _fix_skew(features: pd.DataFrame) -> pd.DataFrame:
    """Apply log1p to right-skewed non-negative features in-place."""
    for col in _LOG_TRANSFORM_COLS:
        if col in features.columns:
            features[col] = np.log1p(features[col])
    return features


def _winsorize(features: pd.DataFrame,
               lower: float = 0.005, upper: float = 0.995,
               min_warmup: int = 252) -> pd.DataFrame:
    """Expanding-window winsorization (causal — no future leakage).

    For row t, percentiles are computed from rows [0..t] only.
    First *min_warmup* rows use the min_warmup-window percentiles
    (not enough history for stable estimates before that).
    """
    result = features.copy()
    lo_bounds = features.expanding(min_periods=min_warmup).quantile(lower)
    hi_bounds = features.expanding(min_periods=min_warmup).quantile(upper)
    for col in features.columns:
        lo = lo_bounds[col]
        hi = hi_bounds[col]
        valid = lo.notna()
        clipped = result.loc[valid, col].copy()
        clipped = clipped.clip(lower=lo[valid].values, upper=hi[valid].values)
        result.loc[valid, col] = clipped
    return result


def _validate_features(features: pd.DataFrame) -> None:
    """Runtime quality checks before features enter the model.

    Raises AssertionError on hard failures, prints warnings otherwise.
    """
    issues = []

    # Check for infinities
    inf_cols = features.columns[features.isin([np.inf, -np.inf]).any()]
    assert len(inf_cols) == 0, (
        f"Features contain inf values: {list(inf_cols)}"
    )

    # Near-zero variance (degenerate feature)
    stds = features.std()
    dead_cols = stds[stds < 1e-8].index.tolist()
    if dead_cols:
        issues.append(f"Near-zero variance: {dead_cols}")

    # Remaining heavy skew after transforms (|skew| > 5)
    skews = features.skew()
    heavy_skew = skews[skews.abs() > 5].index.tolist()
    if heavy_skew:
        issues.append(
            f"Heavy skew after transforms: "
            f"{[(c, f'{skews[c]:.1f}') for c in heavy_skew]}"
        )

    # Pairwise correlations > 0.95 (redundant features)
    corr = features.corr()
    n = len(corr)
    for i in range(n):
        for j in range(i + 1, n):
            r = abs(corr.iloc[i, j])
            if r > 0.95:
                issues.append(
                    f"High correlation ({r:.2f}): "
                    f"{corr.index[i]} <-> {corr.columns[j]}"
                )

    # Heavy tails (kurtosis > 20)
    kurts = features.kurtosis()
    fat_tails = kurts[kurts > 20].index.tolist()
    if fat_tails:
        issues.append(
            f"Extreme kurtosis: "
            f"{[(c, f'{kurts[c]:.0f}') for c in fat_tails]}"
        )

    # ── Stationarity (ADF test) ────────────────────────────────────
    from statsmodels.tsa.stattools import adfuller

    print("\n  Stationarity (ADF test, H0: unit root):")
    non_stationary = []
    for col in features.columns:
        try:
            result = adfuller(features[col].dropna(), maxlag=20, autolag='AIC')
            p = result[1]
            tag = "STATIONARY" if p < 0.05 else "NON-STATIONARY"
            if p >= 0.05:
                non_stationary.append((col, p))
            print(f"    {col:25s}  p={p:.4f}  {tag}")
        except Exception:
            print(f"    {col:25s}  ADF failed")
    if non_stationary:
        issues.append(f"Non-stationary features (ADF p>=0.05): "
                      f"{[(c, f'p={p:.3f}') for c, p in non_stationary]}")

    # ── VIF (multicollinearity) ────────────────────────────────────
    from statsmodels.stats.outliers_influence import variance_inflation_factor

    print("\n  Variance Inflation Factors:")
    X_vif = features.dropna().values
    vif_data = []
    for i, col in enumerate(features.columns):
        try:
            vif = variance_inflation_factor(X_vif, i)
            vif_data.append((col, vif))
        except Exception:
            vif_data.append((col, float('nan')))
    vif_data.sort(key=lambda x: -x[1] if not np.isnan(x[1]) else 0)
    for col, vif in vif_data:
        tag = " *** HIGH" if vif > 10 else ""
        print(f"    {col:25s}  VIF={vif:8.1f}{tag}")
    high_vif = [(c, v) for c, v in vif_data if v > 10]
    if high_vif:
        issues.append(f"High VIF (>10, multicollinear): "
                      f"{[(c, f'VIF={v:.1f}') for c, v in high_vif]}")

    # ── Feature importance (PCA loadings + VIX correlation) ────────
    from sklearn.decomposition import PCA as _DiagPCA

    print("\n  Feature Importance (PCA loadings):")
    n_diag = min(3, len(features.columns))
    _pca = _DiagPCA(n_components=n_diag)
    _pca.fit(features.dropna().values)
    loadings = pd.DataFrame(
        _pca.components_.T,
        index=features.columns,
        columns=[f'PC{i+1}' for i in range(n_diag)],
    )
    loadings['abs_total'] = loadings.abs().sum(axis=1)
    if 'VIX' in features.columns:
        vix_corr = features.corrwith(features['VIX']).abs()
        loadings['|corr_VIX|'] = vix_corr
    loadings = loadings.sort_values('abs_total', ascending=False)
    print(loadings.to_string())
    low_contrib = loadings[loadings['abs_total'] < 0.1].index.tolist()
    if low_contrib:
        issues.append(f"Low PCA contribution (abs_total < 0.1): {low_contrib}")

    # ── Normality (Jarque-Bera) ────────────────────────────────────
    from scipy.stats import jarque_bera

    print("\n  Normality (Jarque-Bera):")
    for col in features.columns:
        stat, p = jarque_bera(features[col].dropna())
        tag = "NORMAL" if p > 0.05 else "non-normal"
        print(f"    {col:25s}  JB={stat:10.1f}  p={p:.4f}  {tag}")

    if issues:
        print("\n  Feature quality warnings:")
        for issue in issues:
            print(f"    - {issue}")
    else:
        print("\n  Feature quality: all checks passed")


# ── Convenience: build + transform + save ───────────────────────────

def prepare_features(market=None):
    """
    Full feature pipeline:  build -> transform -> save.
    If *market* is None, loads from DATA_DIR/market_data.csv.
    """
    os.makedirs(DATA_DIR, exist_ok=True)

    if market is None:
        market = pd.read_csv(
            os.path.join(DATA_DIR, 'market_data.csv'),
            index_col=0, parse_dates=True,
        )

    features = build_features(market)
    features = _fix_skew(features)
    features = _winsorize(features)
    _validate_features(features)

    # Transformed features (log1p + winsorized, NOT standardized).
    # train.py applies its own causal expanding-window standardization.
    features.to_csv(os.path.join(DATA_DIR, 'features_transformed.csv'))

    print(f"Features: {features.shape[1]} indicators x {features.shape[0]} days")
    print(f"  Columns: {list(features.columns)}")

    return features


if __name__ == '__main__':
    prepare_features()
