"""
Feature engineering for PCA -> HMM -> SV pipeline.

Curated feature set (v5 + Phase 5): 21 features spanning distinct regime dimensions.
13 selected for PCA via FEATURE_SUBSET in config.py.

Feature groups:
  - Volatility state    (VIX, VRP)
  - Vol dynamics        (rv_ratio_10_63, vix_ts_slope, SPY_volvol20)
  - Cross-asset risk    (SPY_TLT_corr63, credit_stress)
  - Return dynamics     (SPY_ret, SPY_skew20, SPY_ac1_20)
  - Market structure    (eigen_conc, SPY_dd63)
  - Liquidity           (SPY_rel_volume, SPY_vol_adj_ret)
  - SV-specific         (SPY_rv10_lag5, SPY_rv10_lag10)
  - Leverage / fragility (lev_effect20)
  - Macro (Phase 5)     (HY_OAS, NFCI, yield_curve_slope, GLD_trend)
"""

import pandas as pd
import numpy as np
import os

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from src.config import (
    TICKERS, SHORT_WINDOW, MED_WINDOW, LONG_WINDOW,
    DATA_DIR, MODEL_DIR,
)


# ── Volatility estimators ──────────────────────────────────────────

def _realized_vol(returns: pd.Series, window: int) -> pd.Series:
    """Annualized rolling standard deviation of returns."""
    return returns.rolling(window).std() * np.sqrt(252)


def _parkinson_vol(high: pd.Series, low: pd.Series, window: int) -> pd.Series:
    """Parkinson (1980) high-low volatility estimator, rolling."""
    hl2 = (np.log(high / low)) ** 2 / (4 * np.log(2))
    return np.sqrt(hl2.rolling(window).mean() * 252)


def _garman_klass_vol(
    open_: pd.Series, high: pd.Series,
    low: pd.Series, close: pd.Series,
    window: int,
) -> pd.Series:
    """Garman-Klass (1980) OHLC volatility estimator, rolling."""
    hl2 = 0.5 * (np.log(high / low)) ** 2
    co2 = (2 * np.log(2) - 1) * (np.log(close / open_)) ** 2
    gk  = hl2 - co2
    return np.sqrt(gk.rolling(window).mean().clip(lower=0) * 252)


# ── Feature builder (v2 — curated) ─────────────────────────────────

# All 21 features generated by build_features(), in order.
# 13 are selected by FEATURE_SUBSET (config.py) for PCA.
CURATED_FEATURES = [
    # Volatility state
    'VIX',               # implied vol (market forward expectation)
    'VRP',               # vol risk premium (implied - realized gap)
    # Vol dynamics
    'rv_ratio_10_63',    # vol term structure (short/long; >1 = spike)
    'vix_ts_slope',      # VIX term structure (contango / backwardation)
    'SPY_volvol20',      # vol-of-vol (discrete-time ξ analog)
    # Cross-asset risk
    'SPY_TLT_corr63',   # stock-bond correlation regime
    'credit_stress',     # HY vs Treasury flow (20d rolling)
    # Return dynamics
    'SPY_ret',           # daily log return
    'SPY_skew20',        # rolling skewness (20d)
    'SPY_ac1_20',        # rolling first-order autocorrelation (20d)
    # Market structure
    'eigen_conc',        # eigenvalue concentration (one-factor signal)
    'SPY_dd63',          # 63d drawdown depth
    # Liquidity
    'SPY_rel_volume',    # relative volume vs 20d mean
    'SPY_vol_adj_ret',   # volume-normalized absolute return
    # SV-specific
    'SPY_rv10_lag5',     # lagged realized vol (5d)
    'SPY_rv10_lag10',    # lagged realized vol (10d)
    # Leverage / fragility
    'lev_effect20',      # return-vol correlation (leverage effect)
    # Macro (Phase 5 FRED additions)
    'HY_OAS',              # ICE BofA HY OAS — credit risk premium
    'NFCI',                # Chicago Fed National Financial Conditions Index
    'yield_curve_slope',   # T10Y2Y — canonical macro leading indicator
    'GLD_trend',           # 63d GLD log-momentum — inflation/risk-off proxy
]


# ── Sectioned funnel architecture (Phase 5) ────────────────────────
# Groups CURATED_FEATURES into 4 thematic sections. build_section_signals()
# reduces each section to a single rolling-causal PC1 signal, so each economic
# dimension contributes equally at the HMM input stage regardless of how many
# raw features populate it. See .planning/phases/05-.../05-RESEARCH.md for
# derivation and CFNAI / NFCI analogy.

SECTION_MAP = {
    's_vol': ['VIX', 'VRP', 'rv_ratio_10_63', 'vix_ts_slope', 'SPY_volvol20',
              'SPY_rv10_lag5', 'SPY_rv10_lag10', 'lev_effect20'],
    's_fin': ['credit_stress', 'SPY_TLT_corr63', 'HY_OAS', 'NFCI'],
    's_mac': ['yield_curve_slope', 'GLD_trend', 'SPY_ret', 'SPY_ac1_20'],
    's_str': ['eigen_conc', 'SPY_dd63', 'SPY_rel_volume', 'SPY_vol_adj_ret',
              'SPY_skew20'],
}

# Canonical anchor feature per section: after fitting PCA, if the loading on
# the anchor is negative the sign is flipped. Ensures reproducible sign across
# folds (per 05-RESEARCH.md Pitfall 1 — PCA eigenvector sign is arbitrary).
SECTION_ANCHORS = {
    's_vol': 'VIX',               # positive VIX loading => signal rises with vol
    's_fin': 'HY_OAS',            # positive HY_OAS loading => signal rises with credit stress
    's_mac': 'yield_curve_slope', # positive T10Y2Y => signal rises with expansion
    's_str': 'SPY_dd63',          # SPY_dd63 is negative by construction; anchor flips it positive
}


def _merge_macro_data(market: pd.DataFrame) -> pd.DataFrame:
    """Merge FRED macro columns from data/macro_data.csv onto market DataFrame.

    Phase 5: pulls HY_OAS, NFCI, yield_curve_slope from the macro cache (produced
    by src.data.collect_macro). Causally aligned by index (business-day DatetimeIndex).
    Graceful degradation: if the cache is missing, returns market unchanged with a warning.
    """
    macro_path = os.path.join(DATA_DIR, 'macro_data.csv')
    if not os.path.exists(macro_path):
        print(f"  [features] WARNING: {macro_path} missing — FRED features (HY_OAS, "
              f"NFCI, yield_curve_slope) will be absent. Run src.data.collect_macro first.")
        return market

    macro = pd.read_csv(macro_path, index_col=0, parse_dates=True)
    # Reindex to market's index with forward-fill — causal (no future leakage beyond
    # what collect_macro already enforced).
    macro_aligned = macro.reindex(market.index).ffill()

    # Merge: only add columns that aren't already in market
    enriched = market.copy()
    for col in macro_aligned.columns:
        if col not in enriched.columns:
            enriched[col] = macro_aligned[col]
    return enriched


def build_features(market: pd.DataFrame) -> pd.DataFrame:
    """
    Build curated feature matrix from raw market data.

    21 features spanning distinct regime dimensions — no redundancy.
    Each feature captures one independent axis of market risk state.

    Phase 5: merges FRED macro data (HY_OAS, NFCI, yield_curve_slope) from
    data/macro_data.csv and computes GLD_trend (63d log-momentum).
    """
    market = _merge_macro_data(market)
    f = pd.DataFrame(index=market.index)

    # ── Helper returns (needed for derived features) ───────────────
    spy_close = market.get('SPY_close')
    spy_ret: pd.Series | None = None
    if spy_close is not None:
        spy_ret = pd.Series(np.log(spy_close / spy_close.shift(1)),
                            index=market.index)
        f['SPY_ret'] = spy_ret

    tlt_ret: pd.Series | None = None
    if 'TLT_close' in market.columns:
        tlt_ret = pd.Series(
            np.log(market['TLT_close'] / market['TLT_close'].shift(1)),
            index=market.index)

    hyg_ret: pd.Series | None = None
    if 'HYG_close' in market.columns:
        hyg_ret = pd.Series(
            np.log(market['HYG_close'] / market['HYG_close'].shift(1)),
            index=market.index)

    # ── Volatility state ───────────────────────────────────────────
    rv10: pd.Series | None = None
    rv20: pd.Series | None = None
    rv63: pd.Series | None = None
    if spy_ret is not None:
        rv10 = _realized_vol(spy_ret, SHORT_WINDOW)
        rv20 = _realized_vol(spy_ret, MED_WINDOW)
        rv63 = _realized_vol(spy_ret, LONG_WINDOW)

    if 'VIX' in market.columns:
        f['VIX'] = market['VIX']

    # VRP: VIX - realized vol (20d) in vol points
    if 'VIX' in market.columns and rv20 is not None:
        f['VRP'] = market['VIX'] - rv20 * 100

    # ── Vol dynamics ───────────────────────────────────────────────
    if rv10 is not None and rv63 is not None:
        f['rv_ratio_10_63'] = rv10 / rv63.clip(lower=1e-6)

    if 'VIX' in market.columns and 'VIX3M' in market.columns:
        f['vix_ts_slope'] = market['VIX'] / market['VIX3M'].clip(lower=1) - 1

    # ── Cross-asset risk ───────────────────────────────────────────
    if spy_ret is not None and tlt_ret is not None:
        f['SPY_TLT_corr63'] = spy_ret.rolling(LONG_WINDOW).corr(tlt_ret)

    if hyg_ret is not None and tlt_ret is not None:
        f['credit_stress'] = (hyg_ret - tlt_ret).rolling(MED_WINDOW).mean()

    # ── Macro: FRED pass-through (Phase 5 FEAT-01) ────────────────
    if 'HY_OAS' in market.columns:
        f['HY_OAS'] = market['HY_OAS']
    if 'NFCI' in market.columns:
        f['NFCI'] = market['NFCI']
    if 'yield_curve_slope' in market.columns:
        f['yield_curve_slope'] = market['yield_curve_slope']

    # GLD trend: 63-day log-momentum (causal — uses past LONG_WINDOW days only)
    if 'GLD_close' in market.columns:
        gld = market['GLD_close']
        f['GLD_trend'] = np.log(gld / gld.shift(LONG_WINDOW))

    # ── Return dynamics ────────────────────────────────────────────
    if spy_ret is not None:
        f['SPY_skew20'] = spy_ret.rolling(MED_WINDOW).skew()

    # ── Market structure ───────────────────────────────────────────
    # Eigenvalue concentration: needs multi-asset returns
    ret_cols = []
    for ticker in TICKERS:
        col = f'{ticker}_close'
        if col in market.columns:
            ret_cols.append(np.log(market[col] / market[col].shift(1)))
    if len(ret_cols) >= 3:
        ret_matrix = pd.concat(ret_cols, axis=1).values
        n = len(ret_matrix)
        eigen_vals = np.full(n, np.nan)
        for i in range(LONG_WINDOW - 1, n):
            window = ret_matrix[i - LONG_WINDOW + 1: i + 1]
            if np.isnan(window).any():
                continue
            cov = np.cov(window, rowvar=False)
            eigs = np.linalg.eigvalsh(cov)
            eigs = np.maximum(eigs, 0)
            total = eigs.sum()
            if total > 1e-12:
                eigen_vals[i] = eigs[-1] / total
        f['eigen_conc'] = eigen_vals

    if spy_close is not None:
        rolling_max = spy_close.rolling(LONG_WINDOW).max()
        f['SPY_dd63'] = spy_close / rolling_max - 1

    # ── Additional return dynamics ──────────────────────────────────

    # 22. Rolling first-order autocorrelation (20d, efficient proxy)
    #     ρ̂₁ ≈ Σ(r_t · r_{t-1}) / Σ(r_t²)
    if spy_ret is not None:
        ret_lag = spy_ret.shift(1)
        f['SPY_ac1_20'] = (
            (spy_ret * ret_lag).rolling(MED_WINDOW).sum()
            / (spy_ret ** 2).rolling(MED_WINDOW).sum().clip(lower=1e-12)
        )

    # ── Liquidity ──────────────────────────────────────────────────

    # 23. Relative volume (SPY volume vs 20d mean)
    if 'SPY_volume' in market.columns:
        vol_ma = market['SPY_volume'].rolling(MED_WINDOW).mean()
        f['SPY_rel_volume'] = market['SPY_volume'] / vol_ma.clip(lower=1)

    # 24. Volume-normalized absolute return (fragility proxy)
    if 'SPY_volume' in market.columns and spy_ret is not None:
        norm_vol = market['SPY_volume'] / market['SPY_volume'].rolling(LONG_WINDOW).mean()
        f['SPY_vol_adj_ret'] = spy_ret.abs() / norm_vol.clip(lower=0.1)

    # ── SV-specific features (critical for ρ, ϕ identification) ───

    # 25. Lagged realized vol (SV persistence ϕ support)
    if rv10 is not None:
        f['SPY_rv10_lag5'] = rv10.shift(5)
        f['SPY_rv10_lag10'] = rv10.shift(10)

    # 26. Vol-of-vol estimate (discrete-time ξ analog)
    if rv10 is not None:
        f['SPY_volvol20'] = rv10.rolling(MED_WINDOW).std()

    # 27. Leverage effect proxy (rolling corr between return and lagged vol change)
    #     Empirically measures ρ < 0 in Heston / SV models.
    #     vol_chg is shifted by 1 day for strict causality (avoid same-day info).
    if spy_ret is not None and rv10 is not None:
        vol_chg = rv10.diff().shift(1)
        f['lev_effect20'] = spy_ret.rolling(MED_WINDOW).corr(vol_chg)

    # ── Drop warm-up NaN rows ──────────────────────────────────────
    na_counts = f.isna().sum()
    binding = na_counts[na_counts > 0].sort_values(ascending=False)
    if not binding.empty:
        print(f"  Feature NaN counts (top 5 binding constraints):")
        for feat, cnt in binding.head(5).items():
            print(f"    {feat}: {cnt} NaN rows")

    f = f.dropna()

    assert len(f) >= 252, (
        f"Insufficient data after warm-up: {len(f)} rows (need >= 252). "
        f"Check data availability or reduce LONG_WINDOW."
    )

    return f


# ── Skewness correction ────────────────────────────────────────────

# Features that are non-negative and right-skewed → log(1+x) compresses
# the right tail so PCA doesn't over-weight crisis outliers and the
# symmetric Student-t emissions fit each regime more cleanly.
_LOG_TRANSFORM_COLS = {
    'VIX', 'rv_ratio_10_63',
    'eigen_conc',
}


def _fix_skew(features: pd.DataFrame) -> pd.DataFrame:
    """Apply log1p to right-skewed non-negative features in-place."""
    for col in _LOG_TRANSFORM_COLS:
        if col in features.columns:
            features[col] = np.log1p(features[col])
    return features


def _winsorize(features: pd.DataFrame,
               lower: float = 0.005, upper: float = 0.995,
               min_warmup: int = 252) -> pd.DataFrame:
    """Expanding-window winsorization (causal — no future leakage).

    For row t, percentiles are computed from rows [0..t] only.
    First *min_warmup* rows use the min_warmup-window percentiles
    (not enough history for stable estimates before that).
    """
    result = features.copy()
    lo_bounds = features.expanding(min_periods=min_warmup).quantile(lower)
    hi_bounds = features.expanding(min_periods=min_warmup).quantile(upper)
    for col in features.columns:
        lo = lo_bounds[col]
        hi = hi_bounds[col]
        valid = lo.notna()
        clipped = result.loc[valid, col].copy()
        clipped = clipped.clip(lower=lo[valid].values, upper=hi[valid].values)
        result.loc[valid, col] = clipped
    return result


def _validate_features(features: pd.DataFrame) -> None:
    """Runtime quality checks before features enter the model.
    
    Simplified: Only critical checks run by default.
    Full validation available via DEBUG_FEATURE_VALIDATION flag.
    """
    # Check for infinities
    inf_cols = features.columns[features.isin([np.inf, -np.inf]).any()]
    assert len(inf_cols) == 0, (
        f"Features contain inf values: {list(inf_cols)}"
    )

    # Near-zero variance (degenerate feature)
    stds = features.std()
    dead_cols = stds[stds < 1e-8].index.tolist()
    if dead_cols:
        print(f"  WARNING: Near-zero variance features: {dead_cols}")

# ── Section signal construction (Phase 5 sectioned funnel) ───────────

def _fit_section_signals(df: pd.DataFrame,
                         pca_window: int) -> pd.DataFrame:
    """Core section-signal computation. CALLER controls what rows `df` contains.

    For each section in SECTION_MAP:
      1. Select the subset of features present in the input.
      2. If section has 0 features -> omit from output.
      3. If section has 1 feature -> pass through directly (no PCA).
      4. Otherwise: standardize + PCA(n_components=1) fit on df.iloc[-(pca_window+1):-1]
         (the window ending just BEFORE the last row), sign-correct via SECTION_ANCHORS,
         transform every row in df.

    Causal guarantee: the fit window deliberately excludes the last row so that
    mutating only the last observation never changes output for any prior row.
    This is the strict-causal pattern: for row t the PCA was fit on rows
    [t-pca_window-1 : t-1], meaning row t itself is never in the training window.
    `build_section_signals` (rolling mode) and `build_section_signals_for_fold`
    (fold mode) both delegate here.
    """
    signals = {}
    for section_name, feat_cols in SECTION_MAP.items():
        available = [c for c in feat_cols if c in df.columns]
        if not available:
            continue

        section_df = df[available]

        # Single-feature section: pass-through (no PCA needed or meaningful)
        if len(available) == 1:
            signals[section_name] = section_df.iloc[:, 0].rename(section_name)
            continue

        # Strict-causal fit window: exclude the last row so changing only row t
        # never affects the transform for rows 0..t-1.
        # Shape: pca_window rows from iloc[-(pca_window+1):-1]
        fit_slice = section_df.iloc[-(pca_window + 1):-1].values
        scaler = StandardScaler()
        scaler.fit(fit_slice)
        x_std = scaler.transform(section_df.values)

        # Fit PCA on the same causal window
        pca = PCA(n_components=1, random_state=42)
        pca.fit(x_std[-(pca_window + 1):-1])

        # Sign correction - anchor to canonical feature
        anchor = SECTION_ANCHORS.get(section_name)
        if anchor is not None and anchor in available:
            anchor_idx = available.index(anchor)
            if pca.components_[0, anchor_idx] < 0:
                pca.components_[0] *= -1

        signal = pca.transform(x_std).squeeze()
        signals[section_name] = pd.Series(signal, index=section_df.index,
                                          name=section_name)

    if not signals:
        return pd.DataFrame(index=df.index)
    return pd.DataFrame(signals)


def build_section_signals(features: pd.DataFrame,
                          pca_window: int = 252) -> pd.DataFrame:
    """Reduce sectioned features to one PC1 signal per section (causal, rolling).

    Intended for INFERENCE / PRODUCTION / diagnostic use where the caller
    holds the full history and wants the most recent causal snapshot.
    Do NOT use inside a walk-forward loop - use `build_section_signals_for_fold`
    which makes the training-slice contract structural.

    Args:
        features: DataFrame of raw features (output of build_features()).
        pca_window: Rows used to FIT scaler and PCA (default 252 ~ 1 year).

    Returns:
        DataFrame indexed identically to `features` with one column per non-empty
        section. Column names are the SECTION_MAP keys.

    Causal note: the scaler and PCA are fit on `features.iloc[-pca_window:]`
    only. This mirrors the rolling PCA pattern in prepare_features() and
    orchestrator.walk_forward().
    """
    return _fit_section_signals(features, pca_window)


def build_section_signals_for_fold(features_slice: pd.DataFrame,
                                   pca_window: int = 252) -> pd.DataFrame:
    """Fold-aware variant: caller pre-slices to training window.

    USAGE from walk_forward_section_selection (Plan 04):
        train_slice = features.iloc[train_start:t]   # NEVER includes row t or later
        fold_signals = build_section_signals_for_fold(train_slice, pca_window=252)

    This function has NO access to rows outside `features_slice`; the causal
    guarantee is structural, not advisory. The last `pca_window` rows of the
    passed slice are used to fit; every row in the slice is transformed.

    Args:
        features_slice: DataFrame - already truncated to training rows. Length
                        must be >= pca_window (asserted).
        pca_window:     Rows from the tail of features_slice used to FIT
                        scaler and PCA.

    Returns:
        DataFrame indexed identically to `features_slice` with one column per
        non-empty section. Safe to feed the LAST row into a per-fold MI computation.
    """
    assert len(features_slice) >= pca_window, (
        f"build_section_signals_for_fold: slice has {len(features_slice)} rows, "
        f"need >= {pca_window} to fit section PCA causally"
    )
    return _fit_section_signals(features_slice, pca_window)


# ── Convenience: build + transform + save ───────────────────────────

def prepare_features(market=None, reload_pca=None, pca_window=252):
    """
    Full feature pipeline:  build -> transform -> save.

    Args:
        market: DataFrame with market data. If None, loads from DATA_DIR/market_data.csv.
        reload_pca: Optional fitted PCA object from prior run. If provided, uses it instead of computing new.
        pca_window: Number of trading days for rolling PCA refit (default 252 = 1 year).

    Returns:
        Tuple: (features_df, pca_fitted_object)
            - features_df: DataFrame with PCA-transformed features
            - pca_fitted_object: Fitted scikit-learn PCA object (for checkpoint)
    """
    from sklearn.decomposition import PCA

    os.makedirs(DATA_DIR, exist_ok=True)

    if market is None:
        market = pd.read_csv(
            os.path.join(DATA_DIR, 'market_data.csv'),
            index_col=0, parse_dates=True,
        )

    features = build_features(market)
    features = _fix_skew(features)
    features = _winsorize(features)
    _validate_features(features)

    # Transformed features (log1p + winsorized, NOT standardized).
    # train.py applies its own causal expanding-window standardization.
    features.to_csv(os.path.join(DATA_DIR, 'features_transformed.csv'))

    print(f"Features: {features.shape[1]} indicators x {features.shape[0]} days")
    print(f"  Columns: {list(features.columns)}")

    # PCA state management (for incremental mode)
    # Per D-07: Rolling PCA refit on latest pca_window rows (causal, no future data)
    if reload_pca is None:
        # Compute PCA from scratch on latest pca_window rows
        fit_data = features.iloc[-pca_window:, :].values
        pca = PCA(n_components=5, random_state=42)
        pca.fit(fit_data)
        print(f"  PCA fitted on latest {pca_window} rows; explained variance: {pca.explained_variance_ratio_.sum():.1%}")
    else:
        # Use reloaded PCA
        pca = reload_pca
        print(f"  Using reloaded PCA from checkpoint")

    # Transform all features using PCA
    X_pca = pca.transform(features.values)
    pca_features = pd.DataFrame(
        X_pca,
        columns=[f'PC{i+1}' for i in range(X_pca.shape[1])],
        index=features.index,
    )

    return pca_features, pca


if __name__ == '__main__':
    prepare_features()
