"""Regenerate paper/TABLES.md from the frozen one-look artifacts (results/stage1.csv,
allocation_summary.csv, allocation_controls.csv). Numbers only ever come from evidence
files — never typed by hand. Rerun: .venv/Scripts/python paper/build_tables.py"""

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def fmt(v, d=1):
    return f"{float(v):+.{d}f}" if isinstance(v, (int, float)) or str(v).replace(
        ".", "").replace("-", "").isdigit() else str(v)


def main():
    s1 = pd.read_csv(ROOT / "results" / "stage1.csv").iloc[0]
    s2 = pd.read_csv(ROOT / "results" / "allocation_summary.csv",
                     keep_default_na=False, na_values=[""]).iloc[0]
    ctl = pd.read_csv(ROOT / "results" / "allocation_controls.csv")

    L = []
    L.append("# Appendix tables — exact numbers from the frozen artifacts\n")
    L.append("Generated by `paper/build_tables.py`; sources: `results/stage1.csv`, "
             "`results/allocation_summary.csv`, `results/allocation_controls.csv`. "
             "All fees are FKO quadratic-utility fees, annualized bps/yr, 90% CIs from "
             "the paired stationary bootstrap (mean block 126d, B=2000, seed 0).\n")

    L.append("## Table 1 — Experiment 1 (overlay on equity), primary and controls\n")
    L.append("| Quantity | Value |")
    L.append("|---|---|")
    L.append(f"| fee(JM − B&H), γ=10 | {fmt(s1['fee'])} [{fmt(s1['ci_lo'])}, {fmt(s1['ci_hi'])}] |")
    L.append(f"| fee(JM − VT), γ=10 (honest bar) | {fmt(s1['fee_vt'])} [{fmt(s1['ci_vt_lo'])}, {fmt(s1['ci_vt_hi'])}] |")
    L.append(f"| fee(JM − B&H), γ=1 | {fmt(s1['fee_g1'])} |")
    L.append(f"| fee(JM − SMA200) | {fmt(s1['fee_sma'])} |")
    L.append(f"| fee(JM − exposure-matched static mix) | {fmt(s1['fee_mix'])} |")
    L.append(f"| same-close (delay=1) sensitivity | {fmt(s1['fee_delay1'])} |")
    L.append(f"| break-even one-way cost | {float(s1['breakeven_bps']):.1f} bps |")
    L.append(f"| C1 placebo 95th percentile (n=100) | {fmt(s1['c1_bar'])} |")
    L.append(f"| C2 surrogate band max (n=10) | {fmt(s1['c2_max'])} |")
    L.append(f"| C3 iid band max (n=10) | {fmt(s1['c3_max'])} |")
    L.append(f"| ΔSharpe(JM−B&H) 90% CI | [{float(s1['dsr_lo']):.3f}, {float(s1['dsr_hi']):.3f}] |")
    L.append(f"| label stability, train-start +2y / −2y | {float(s1['stab_start+2y']):.3f} / {float(s1['stab_start-2y']):.3f} |")
    L.append(f"| era-half fees 1990–2007 / 2008–2026 | {fmt(s1['half_1990_2007'])} / {fmt(s1['half_2008_2026'])} |")
    L.append(f"| switches/yr | {float(s1['switches_yr']):.2f} |")
    L.append(f"| frozen classification | Case {s1['case']} |\n")

    L.append("## Table 2 — Experiment 2 (conditional allocation), primary and controls\n")
    L.append("| Quantity | Value |")
    L.append("|---|---|")
    L.append(f"| fee_A(cond − B_match), γ=10, full window | {fmt(s2['fee_a'])} [{fmt(s2['ci_a_lo'])}, {fmt(s2['ci_a_hi'])}] |")
    L.append(f"| fee_B(cond − B_react), γ=10, from activation | {fmt(s2['fee_b'])} [{fmt(s2['ci_b_lo'])}, {fmt(s2['ci_b_hi'])}] |")
    L.append(f"| fee_A / fee_B at γ=1 | {fmt(s2['fee_a_g1'])} / {fmt(s2['fee_b_g1'])} |")
    for name, tag in (("C1_placebo", "placebo (n=100)"), ("C2_shuffle", "episode-shuffle (n=50)"),
                      ("C3_iid", "iid panels (n=20)")):
        sub = ctl[ctl["control"] == name]
        L.append(f"| {tag}: fee_A 5–95th | [{sub['fee_a'].quantile(0.05):+.1f}, {sub['fee_a'].quantile(0.95):+.1f}] |")
        L.append(f"| {tag}: fee_B 5–95th | [{sub['fee_b'].quantile(0.05):+.1f}, {sub['fee_b'].quantile(0.95):+.1f}] |")
    L.append(f"| vol-of-vol, cond / B_match (F2) | {float(s2['volvol_cond']) * 100:.2f} / {float(s2['volvol_match']) * 100:.2f} pp |")
    L.append(f"| turnover/yr, cond / B_match / B_react | {float(s2['turnover_cond']):.2f} / {float(s2['turnover_match']):.2f} / {float(s2['turnover_react']):.2f} |")
    L.append(f"| ΔSharpe(cond−B_match) 90% CI | [{float(s2['dsr_lo']):.3f}, {float(s2['dsr_hi']):.3f}] |")
    L.append(f"| era splits fee_A (pre/post-2000, ex-2022, from-act) | {fmt(s2['split_pre2000_a'])} / {fmt(s2['split_post2000_a'])} / {fmt(s2['split_ex2022ep_a'])} / {fmt(s2['split_from_act_a'])} |")
    L.append(f"| era splits fee_B (pre/post-2000, ex-2022, from-act) | {fmt(s2['split_pre2000_b'])} / {fmt(s2['split_post2000_b'])} / {fmt(s2['split_ex2022ep_b'])} / {fmt(s2['split_from_act_b'])} |")
    L.append(f"| conditioning activation | {s2['activation']} |")
    L.append(f"| falsifiers F1 / F1b / F2 / F3 | {s2['f1']} / {s2['f1b']} / {s2['f2']} / {s2['f3']} |")
    L.append(f"| frozen classification | {s2['verdict']} |\n")

    L.append("## Table 3 — Experiment 2 arm summary (scored window)\n")
    L.append("| Arm | Ann. return | Ann. vol | Sharpe | MaxDD |")
    L.append("|---|---|---|---|---|")
    for nm, key in (("Conditional ERC", "cond"), ("B_match (uncond. expanding)", "B_match"),
                    ("B_react (EWMA λ=0.97)", "B_react"), ("60/40", "60_40"),
                    ("VT equity", "VT_eq"), ("B&H equity", "BH_eq")):
        L.append(f"| {nm} | {float(s2[f'{key}_ann_ret']) * 100:.2f}% "
                 f"| {float(s2[f'{key}_ann_vol']) * 100:.2f}% "
                 f"| {float(s2[f'{key}_sharpe']):.3f} "
                 f"| {float(s2[f'{key}_maxdd']) * 100:.1f}% |")
    L.append("")

    out = ROOT / "paper" / "TABLES.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
